package com.vaadin.tutorial.addressbook;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContactFormLayout extends VerticalLayout {
	protected FormLayout formLayout;
	protected HorizontalLayout horizontalLayout;
	protected Button save;
	protected Button cancel;
	protected TextField firstName;
	protected TextField lastName;
	protected TextField phone;
	protected TextField email;
	protected DateField birthDate;

	public ContactFormLayout() {
		Design.read(this);
	}
}
